function z_dot = SRDt_reduced_dynamics_ode(t, z, Phi, Phi_prm, Phi_2prm)
     z_dot = [z(2); -1/get_alpha(Phi, Phi_prm)*...
                    (get_gamma(Phi) + ...
                        get_beta(Phi, Phi_prm, Phi_2prm)*z(2)^2)];
end